package io.justdevit.telegram.flow.model

/**
 * Captures a snapshot of the execution of a single chat flow step.
 *
 * This class encapsulates the executed step, its associated context during
 * execution, and the resulting output of the step's execution. It is designed
 * to track and represent the state of a step's execution within a chat flow.
 *
 * @property executedStep The chat step that was executed.
 * @property context The context in which the chat step was executed, including relevant state and flow details.
 * @property result The outcome of the chat step execution, including any data or status generated by the step.
 */
data class ChatStepExecutionSnapshot(
    val executedStep: ChatStep,
    val context: ChatStepContext,
    val result: ChatStepExecutionResult,
)
